<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx16xQQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx16xQQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx16xQQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx16xQQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx16xQQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx16xQQ',
    'container.build_id' => '52b045ff',
    'container.build_time' => 1681402179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx16xQQ');
