<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIh96Roh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIh96Roh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIh96Roh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIh96Roh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIh96Roh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ih96Roh',
    'container.build_id' => '06b5d359',
    'container.build_time' => 1681380100,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIh96Roh');
